import { Metadata } from 'next'
import { ShieldCheck, Hash, Dices, Eye } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Provably Fair | FORTUNA CASINO',
  description: 'Learn how Fortuna Casino uses HMAC-SHA256 cryptography to ensure every game outcome is provably fair and independently verifiable.',
}

export default function ProvablyFairPage() {
  return (
    <div className="min-h-screen bg-[var(--casino-bg)] py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-10">
          <div className="flex items-center gap-3 mb-3">
            <ShieldCheck className="w-8 h-8 text-[var(--casino-green)]" />
            <h1 className="text-3xl font-bold text-white">Provably Fair</h1>
          </div>
          <p className="text-[var(--casino-text-muted)]">
            Every game on Fortuna Casino is cryptographically verifiable. We cannot
            manipulate outcomes, and you can prove it.
          </p>
        </div>

        <div className="space-y-10 text-[var(--casino-text-muted)] leading-relaxed">
          {/* What is Provably Fair */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              What is Provably Fair?
            </h2>
            <p>
              Provably fair is a cryptographic system that allows players to independently
              verify that game outcomes were determined fairly and were not manipulated by
              the casino. Unlike traditional online casinos that require you to trust
              third-party audits, a provably fair system gives you the mathematical tools
              to verify every single game result yourself.
            </p>
          </section>

          {/* The Three Components */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">
              The Three Components
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Server Seed */}
              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-5">
                <div className="w-10 h-10 rounded-lg bg-[var(--casino-accent)]/10 flex items-center justify-center mb-3">
                  <Hash className="w-5 h-5 text-[var(--casino-accent)]" />
                </div>
                <h3 className="text-white font-semibold mb-2">Server Seed</h3>
                <p className="text-sm">
                  A random string generated by our server. Before any game begins, you
                  receive a <span className="text-white font-medium">hashed version</span>{' '}
                  (SHA-256) of this seed. The actual server seed is kept secret until the
                  game round ends or you choose to rotate seeds, at which point it is
                  revealed for verification.
                </p>
              </div>

              {/* Client Seed */}
              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-5">
                <div className="w-10 h-10 rounded-lg bg-[var(--casino-green)]/10 flex items-center justify-center mb-3">
                  <Dices className="w-5 h-5 text-[var(--casino-green)]" />
                </div>
                <h3 className="text-white font-semibold mb-2">Client Seed</h3>
                <p className="text-sm">
                  A string that <span className="text-white font-medium">you provide</span>{' '}
                  or is generated by your browser. You can change this seed at any time.
                  Because you control this input, the casino cannot predict the final
                  outcome in advance, as it depends on your contribution.
                </p>
              </div>

              {/* Nonce */}
              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-5">
                <div className="w-10 h-10 rounded-lg bg-[var(--casino-purple)]/10 flex items-center justify-center mb-3">
                  <Eye className="w-5 h-5 text-[var(--casino-purple)]" />
                </div>
                <h3 className="text-white font-semibold mb-2">Nonce</h3>
                <p className="text-sm">
                  A counter that increments with each bet you place. The nonce ensures that
                  even with the same server seed and client seed, every game round produces
                  a <span className="text-white font-medium">unique result</span>. It
                  starts at 0 and increases by 1 for each game.
                </p>
              </div>
            </div>
          </section>

          {/* How It Works — Visual Flow */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">
              How It Works
            </h2>

            {/* Flow Diagram */}
            <div className="space-y-3">
              {/* Step 1 */}
              <div className="flex items-stretch gap-3">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[var(--casino-accent)] flex items-center justify-center text-black font-bold text-sm shrink-0">
                    1
                  </div>
                  <div className="w-0.5 flex-1 bg-[var(--casino-border)] mt-2" />
                </div>
                <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4 flex-1 mb-1">
                  <h4 className="text-white font-medium mb-1">Server Generates Seed</h4>
                  <p className="text-sm">
                    Before the game begins, the server creates a random{' '}
                    <span className="text-[var(--casino-accent)] font-mono">server_seed</span>{' '}
                    and sends you only its SHA-256 hash. This hash acts as a commitment —
                    it locks in the server seed without revealing it.
                  </p>
                  <div className="mt-3 rounded-lg bg-[var(--casino-bg)] border border-[var(--casino-border)] p-3 font-mono text-xs overflow-x-auto">
                    <span className="text-[var(--casino-text-muted)]">server_seed_hash = </span>
                    <span className="text-[var(--casino-accent)]">SHA256</span>
                    <span className="text-white">(server_seed)</span>
                  </div>
                </div>
              </div>

              {/* Step 2 */}
              <div className="flex items-stretch gap-3">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[var(--casino-accent)] flex items-center justify-center text-black font-bold text-sm shrink-0">
                    2
                  </div>
                  <div className="w-0.5 flex-1 bg-[var(--casino-border)] mt-2" />
                </div>
                <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4 flex-1 mb-1">
                  <h4 className="text-white font-medium mb-1">Player Provides Client Seed</h4>
                  <p className="text-sm">
                    You set your own{' '}
                    <span className="text-[var(--casino-green)] font-mono">client_seed</span>{' '}
                    (or accept the auto-generated one). This is your contribution to the
                    randomness — the server cannot control or predict what you choose.
                  </p>
                </div>
              </div>

              {/* Step 3 */}
              <div className="flex items-stretch gap-3">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[var(--casino-accent)] flex items-center justify-center text-black font-bold text-sm shrink-0">
                    3
                  </div>
                  <div className="w-0.5 flex-1 bg-[var(--casino-border)] mt-2" />
                </div>
                <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4 flex-1 mb-1">
                  <h4 className="text-white font-medium mb-1">Game Outcome is Computed</h4>
                  <p className="text-sm">
                    The result is calculated using HMAC-SHA256 with the server seed as the
                    key and a combination of the client seed and nonce as the message. This
                    produces a deterministic but unpredictable output.
                  </p>
                  <div className="mt-3 rounded-lg bg-[var(--casino-bg)] border border-[var(--casino-border)] p-3 font-mono text-xs overflow-x-auto">
                    <span className="text-[var(--casino-text-muted)]">result = </span>
                    <span className="text-[var(--casino-accent)]">HMAC-SHA256</span>
                    <span className="text-white">(server_seed, client_seed + &quot;:&quot; + nonce)</span>
                  </div>
                </div>
              </div>

              {/* Step 4 */}
              <div className="flex items-stretch gap-3">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[var(--casino-accent)] flex items-center justify-center text-black font-bold text-sm shrink-0">
                    4
                  </div>
                  <div className="w-0.5 flex-1 bg-[var(--casino-border)] mt-2" />
                </div>
                <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4 flex-1 mb-1">
                  <h4 className="text-white font-medium mb-1">Hex to Game Value</h4>
                  <p className="text-sm">
                    The HMAC output (a 64-character hex string) is converted into a game
                    value. For example, the first 8 characters are parsed as a hexadecimal
                    number and mapped to a game-specific range (e.g., a crash multiplier,
                    card value, or roulette number).
                  </p>
                  <div className="mt-3 rounded-lg bg-[var(--casino-bg)] border border-[var(--casino-border)] p-3 font-mono text-xs overflow-x-auto">
                    <span className="text-[var(--casino-text-muted)]">hex = </span>
                    <span className="text-white">result.substring(0, 8)</span>
                    <br />
                    <span className="text-[var(--casino-text-muted)]">decimal = </span>
                    <span className="text-[var(--casino-accent)]">parseInt</span>
                    <span className="text-white">(hex, 16)</span>
                    <br />
                    <span className="text-[var(--casino-text-muted)]">game_value = </span>
                    <span className="text-white">decimal % range + offset</span>
                  </div>
                </div>
              </div>

              {/* Step 5 */}
              <div className="flex items-stretch gap-3">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[var(--casino-green)] flex items-center justify-center text-black font-bold text-sm shrink-0">
                    5
                  </div>
                </div>
                <div className="rounded-xl border border-[var(--casino-green)]/30 bg-[var(--casino-green)]/5 p-4 flex-1">
                  <h4 className="text-white font-medium mb-1">Verify After the Game</h4>
                  <p className="text-sm">
                    After rotating your server seed (or at the end of a seed session), the
                    original server seed is revealed. You can then hash it yourself and
                    confirm it matches the hash you received in Step 1. Recompute the HMAC
                    to verify every past game outcome.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Visual Diagram */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">
              Verification Flow
            </h2>
            <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-6 overflow-x-auto">
              <div className="min-w-[500px]">
                {/* Inputs Row */}
                <div className="flex items-center justify-center gap-4 mb-4">
                  <div className="rounded-lg border border-[var(--casino-accent)]/50 bg-[var(--casino-accent)]/10 px-4 py-2 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)]">Server</div>
                    <div className="text-sm text-[var(--casino-accent)] font-mono font-medium">
                      server_seed
                    </div>
                  </div>
                  <div className="text-[var(--casino-text-muted)] text-lg">+</div>
                  <div className="rounded-lg border border-[var(--casino-green)]/50 bg-[var(--casino-green)]/10 px-4 py-2 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)]">Player</div>
                    <div className="text-sm text-[var(--casino-green)] font-mono font-medium">
                      client_seed
                    </div>
                  </div>
                  <div className="text-[var(--casino-text-muted)] text-lg">+</div>
                  <div className="rounded-lg border border-[var(--casino-purple)]/50 bg-[var(--casino-purple)]/10 px-4 py-2 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)]">Counter</div>
                    <div className="text-sm text-[var(--casino-purple)] font-mono font-medium">
                      nonce
                    </div>
                  </div>
                </div>

                {/* Arrow Down */}
                <div className="flex justify-center mb-4">
                  <div className="flex flex-col items-center">
                    <div className="w-0.5 h-6 bg-[var(--casino-border)]" />
                    <div className="w-0 h-0 border-l-[6px] border-r-[6px] border-t-[8px] border-l-transparent border-r-transparent border-t-[var(--casino-border)]" />
                  </div>
                </div>

                {/* HMAC Box */}
                <div className="flex justify-center mb-4">
                  <div className="rounded-xl border-2 border-[var(--casino-accent)]/60 bg-[var(--casino-bg)] px-6 py-3 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)] mb-1">
                      Cryptographic Function
                    </div>
                    <div className="text-lg font-bold text-[var(--casino-accent)] font-mono">
                      HMAC-SHA256
                    </div>
                  </div>
                </div>

                {/* Arrow Down */}
                <div className="flex justify-center mb-4">
                  <div className="flex flex-col items-center">
                    <div className="w-0.5 h-6 bg-[var(--casino-border)]" />
                    <div className="w-0 h-0 border-l-[6px] border-r-[6px] border-t-[8px] border-l-transparent border-r-transparent border-t-[var(--casino-border)]" />
                  </div>
                </div>

                {/* Output */}
                <div className="flex justify-center mb-4">
                  <div className="rounded-lg border border-[var(--casino-border)] bg-[var(--casino-bg)] px-4 py-2 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)]">Output</div>
                    <div className="text-sm text-white font-mono">
                      a3f8b2c1d4e5...
                    </div>
                  </div>
                </div>

                {/* Arrow Down */}
                <div className="flex justify-center mb-4">
                  <div className="flex flex-col items-center">
                    <div className="w-0.5 h-6 bg-[var(--casino-border)]" />
                    <div className="w-0 h-0 border-l-[6px] border-r-[6px] border-t-[8px] border-l-transparent border-r-transparent border-t-[var(--casino-border)]" />
                  </div>
                </div>

                {/* Game Result */}
                <div className="flex justify-center">
                  <div className="rounded-xl border-2 border-[var(--casino-green)]/60 bg-[var(--casino-green)]/5 px-6 py-3 text-center">
                    <div className="text-xs text-[var(--casino-text-muted)] mb-1">
                      Deterministic Result
                    </div>
                    <div className="text-lg font-bold text-[var(--casino-green)]">
                      Game Outcome
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Why This Ensures Fairness */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Why This Ensures Games Cannot Be Rigged
            </h2>
            <div className="space-y-4">
              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4">
                <h4 className="text-white font-medium mb-2">
                  The server seed is committed before you play
                </h4>
                <p className="text-sm">
                  By hashing the server seed and showing you the hash before any bets are
                  placed, the casino is cryptographically locked into a specific seed. It
                  cannot be changed after you start playing. Any attempt to alter the
                  server seed would produce a different hash, which you would detect.
                </p>
              </div>

              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4">
                <h4 className="text-white font-medium mb-2">
                  You contribute to the randomness
                </h4>
                <p className="text-sm">
                  Your client seed is an input to the HMAC function. Since the casino does
                  not know your client seed in advance (and you can change it at any time),
                  it cannot predict or precompute the game outcome. Both parties must
                  contribute for the result to be generated.
                </p>
              </div>

              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4">
                <h4 className="text-white font-medium mb-2">
                  HMAC-SHA256 is a one-way function
                </h4>
                <p className="text-sm">
                  The HMAC-SHA256 algorithm is a widely trusted cryptographic standard used
                  in banking, security protocols, and blockchain technology. It is
                  computationally infeasible to reverse-engineer the inputs from the output,
                  and even a single-bit change in any input produces a completely different
                  result.
                </p>
              </div>

              <div className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4">
                <h4 className="text-white font-medium mb-2">
                  Full transparency after the fact
                </h4>
                <p className="text-sm">
                  Once the server seed is revealed (after rotation), you have all three
                  inputs: server seed, client seed, and nonce. You can recompute the HMAC
                  using any standard tool or programming language to confirm the exact game
                  outcome. No trust required — only math.
                </p>
              </div>
            </div>
          </section>

          {/* How to Verify */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              How to Verify Your Results
            </h2>
            <p className="mb-4">
              Follow these steps to independently verify any past game result:
            </p>
            <ol className="list-decimal list-inside space-y-3 ml-2">
              <li>
                <span className="text-white font-medium">Get the revealed server seed</span>{' '}
                — After rotating your seed pair, the previous server seed is disclosed in
                your account settings or game history.
              </li>
              <li>
                <span className="text-white font-medium">
                  Confirm the server seed hash
                </span>{' '}
                — Hash the revealed server seed with SHA-256 and compare it to the hash
                you were given before the game. They must match exactly.
              </li>
              <li>
                <span className="text-white font-medium">Gather your inputs</span> — Note
                your client seed and the nonce for the specific game round you want to
                verify.
              </li>
              <li>
                <span className="text-white font-medium">Compute the HMAC</span> — Using
                HMAC-SHA256, set the server seed as the key and{' '}
                <code className="text-[var(--casino-accent)] bg-[var(--casino-bg)] px-1.5 py-0.5 rounded text-xs font-mono">
                  client_seed:nonce
                </code>{' '}
                as the message.
              </li>
              <li>
                <span className="text-white font-medium">Convert to game value</span> —
                Take the first 8 hex characters of the HMAC output, convert to a decimal,
                and apply the game-specific formula.
              </li>
              <li>
                <span className="text-white font-medium">Compare</span> — The calculated
                game value should exactly match the outcome you experienced in the game.
              </li>
            </ol>

            {/* Code Example */}
            <div className="mt-6 rounded-xl border border-[var(--casino-border)] bg-[var(--casino-bg)] p-4 overflow-x-auto">
              <div className="text-xs text-[var(--casino-text-muted)] mb-2">
                JavaScript verification example
              </div>
              <pre className="font-mono text-sm text-white leading-relaxed">
{`const crypto = require('crypto');

function verify(serverSeed, clientSeed, nonce) {
  // Step 1: Verify server seed matches its hash
  const hash = crypto
    .createHash('sha256')
    .update(serverSeed)
    .digest('hex');
  console.log('Server seed hash:', hash);

  // Step 2: Compute HMAC-SHA256
  const message = clientSeed + ':' + nonce;
  const hmac = crypto
    .createHmac('sha256', serverSeed)
    .update(message)
    .digest('hex');
  console.log('HMAC result:', hmac);

  // Step 3: Convert to game value
  const hex = hmac.substring(0, 8);
  const decimal = parseInt(hex, 16);
  console.log('Decimal value:', decimal);

  return decimal;
}`}
              </pre>
            </div>
          </section>

          {/* FAQ */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">
              Frequently Asked Questions
            </h2>
            <div className="space-y-3">
              {[
                {
                  q: 'Can the casino change the server seed after I place a bet?',
                  a: 'No. The server seed is hashed and committed before you place any bets. Changing the seed would change the hash, which you can detect. The commitment is cryptographically binding.',
                },
                {
                  q: 'Why can\'t I see the server seed during an active session?',
                  a: 'If you could see the server seed while it was still in use, you could predict future game outcomes (since you already know your client seed and the nonce is sequential). The seed is revealed only after rotation to maintain unpredictability.',
                },
                {
                  q: 'What if I don\'t change my client seed?',
                  a: 'A default client seed is automatically generated for you. You can change it at any time. Even with the default, the system remains provably fair because the nonce changes with each game round.',
                },
                {
                  q: 'Can I use third-party tools to verify?',
                  a: 'Absolutely. Any tool or programming language that supports HMAC-SHA256 can verify results. There are also independent online provably fair verification tools available.',
                },
                {
                  q: 'Is this the same system used by other provably fair casinos?',
                  a: 'Yes. HMAC-SHA256 with server seed, client seed, and nonce is the industry standard for provably fair gaming. The specific implementation details (such as how the hex output maps to game values) may vary by game.',
                },
              ].map((item, i) => (
                <div
                  key={i}
                  className="rounded-xl border border-[var(--casino-border)] bg-[var(--casino-surface)] p-4"
                >
                  <h4 className="text-white font-medium mb-2">{item.q}</h4>
                  <p className="text-sm">{item.a}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Footer */}
          <div className="border-t border-[var(--casino-border)] pt-6 mt-10">
            <p className="text-xs text-[var(--casino-text-muted)]">
              &copy; 2026 Fortuna Casino. All rights reserved. Our provably fair system is
              open for inspection and verification. If you have questions about our
              implementation, contact us at{' '}
              <a
                href="mailto:support@fortunacasino.com"
                className="text-[var(--casino-accent)] hover:underline"
              >
                support@fortunacasino.com
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
