export interface GameInfo {
  id: string
  slug: string
  name: string
  category: 'slots' | 'table' | 'instant' | 'card'
  description: string
  icon: string
  houseEdge: string
  isHot?: boolean
  isNew?: boolean
  href: string
  minBet: number
  maxBet: number
  features?: string[]
  theme?: string
  volatility?: 'low' | 'medium' | 'high'
  rtp?: number
}

export const GAME_CATALOG: GameInfo[] = [
  // ═══════════════════════════════════════════════════
  //  PLAYABLE GAMES (link to actual game pages)
  // ═══════════════════════════════════════════════════
  {
    id: 'slots',
    slug: 'slots',
    name: 'Mega Slots',
    category: 'slots',
    description: 'Classic 3x3 slot machine with wilds and 5 paylines',
    icon: '🎰',
    houseEdge: '3%',
    isHot: true,
    href: '/games/slots',
    minBet: 100,
    maxBet: 100000,
    features: ['Wilds', '5 Paylines', 'Jackpot'],
    theme: 'classic',
    volatility: 'medium',
    rtp: 97,
  },
  {
    id: 'blackjack',
    slug: 'blackjack',
    name: 'Blackjack',
    category: 'table',
    description: '6-deck shoe, split, double down, 3:2 blackjack',
    icon: '🃏',
    houseEdge: '0.5%',
    href: '/games/blackjack',
    minBet: 100,
    maxBet: 500000,
    features: ['Split', 'Double Down', 'Insurance'],
    theme: 'classic',
    volatility: 'low',
    rtp: 99.5,
  },
  {
    id: 'roulette',
    slug: 'roulette',
    name: 'European Roulette',
    category: 'table',
    description: 'European roulette with all bet types',
    icon: '🎡',
    houseEdge: '2.7%',
    href: '/games/roulette',
    minBet: 100,
    maxBet: 500000,
    features: ['Inside Bets', 'Outside Bets'],
    theme: 'classic',
    volatility: 'medium',
    rtp: 97.3,
  },
  {
    id: 'poker',
    slug: 'poker',
    name: 'Video Poker',
    category: 'card',
    description: 'Jacks or Better with hold/draw',
    icon: '♠️',
    houseEdge: '0.5%',
    isNew: true,
    href: '/games/poker',
    minBet: 100,
    maxBet: 100000,
    features: ['Jacks or Better', 'Hold/Draw'],
    theme: 'classic',
    volatility: 'medium',
    rtp: 99.5,
  },
  {
    id: 'dice',
    slug: 'dice',
    name: 'Dice',
    category: 'instant',
    description: 'Roll over/under with adjustable odds',
    icon: '🎲',
    houseEdge: '1%',
    href: '/games/dice',
    minBet: 100,
    maxBet: 500000,
    features: ['Adjustable Odds'],
    theme: 'classic',
    volatility: 'medium',
    rtp: 99,
  },
  {
    id: 'crash',
    slug: 'crash',
    name: 'Crash',
    category: 'instant',
    description: 'Cash out before the multiplier crashes',
    icon: '📈',
    houseEdge: '1%',
    isHot: true,
    href: '/games/crash',
    minBet: 100,
    maxBet: 500000,
    features: ['Auto Cash Out', 'Up to 1000x'],
    theme: 'modern',
    volatility: 'high',
    rtp: 99,
  },
  {
    id: 'plinko',
    slug: 'plinko',
    name: 'Plinko',
    category: 'instant',
    description: '16-row Plinko board with up to 110x multiplier',
    icon: '⚡',
    houseEdge: '1%',
    isNew: true,
    href: '/games/plinko',
    minBet: 100,
    maxBet: 100000,
    features: ['16 Rows', 'Up to 110x'],
    theme: 'modern',
    volatility: 'high',
    rtp: 99,
  },
  {
    id: 'coinflip',
    slug: 'coinflip',
    name: 'Coin Flip',
    category: 'instant',
    description: 'Heads or tails, 1.98x payout',
    icon: '🪙',
    houseEdge: '1%',
    href: '/games/coinflip',
    minBet: 100,
    maxBet: 500000,
    features: ['50/50 Odds'],
    theme: 'classic',
    volatility: 'low',
    rtp: 99,
  },

  // ═══════════════════════════════════════════════════
  //  SLOT THEMES (35+ from source casino project)
  // ═══════════════════════════════════════════════════
  {
    id: 'wicked-circus',
    slug: 'wicked-circus',
    name: 'Wicked Circus',
    category: 'slots',
    description: 'Dark circus themed slots with sinister free spins and expanding wilds',
    icon: '🎪',
    houseEdge: '4%',
    isHot: true,
    href: '/games/slots?theme=wicked-circus',
    minBet: 100,
    maxBet: 50000,
    features: ['Free Spins', 'Expanding Wilds', 'Bonus Round'],
    theme: 'circus',
    volatility: 'high',
    rtp: 96,
  },
  {
    id: 'incinerator',
    slug: 'incinerator',
    name: 'Incinerator',
    category: 'slots',
    description: 'Blazing hot reels with cascading wins and fiery multipliers',
    icon: '🔥',
    houseEdge: '3.5%',
    href: '/games/slots?theme=incinerator',
    minBet: 100,
    maxBet: 50000,
    features: ['Cascading Wins', 'Multipliers', 'Wilds'],
    theme: 'fire',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'wild-mantra',
    slug: 'wild-mantra',
    name: 'Wild Mantra',
    category: 'slots',
    description: 'Mystical Eastern-themed slot with expanding reels and meditation bonus',
    icon: '🕉️',
    houseEdge: '3.8%',
    isNew: true,
    href: '/games/slots?theme=wild-mantra',
    minBet: 100,
    maxBet: 75000,
    features: ['Expanding Reels', 'Free Spins', 'Meditation Bonus'],
    theme: 'mythology',
    volatility: 'medium',
    rtp: 96.2,
  },
  {
    id: 'beauty-beast',
    slug: 'beauty-beast',
    name: 'Beauty & Beast',
    category: 'slots',
    description: 'Enchanted castle reels with rose wilds and beast mode free spins',
    icon: '🌹',
    houseEdge: '3.5%',
    href: '/games/slots?theme=beauty-beast',
    minBet: 100,
    maxBet: 50000,
    features: ['Rose Wilds', 'Beast Mode', 'Free Spins'],
    theme: 'fairy-tale',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'dark-joke-rises',
    slug: 'dark-joke-rises',
    name: 'Dark Joke Rises',
    category: 'slots',
    description: 'Gotham-inspired slot with joker wilds and chaos multipliers',
    icon: '🃏',
    houseEdge: '4%',
    isHot: true,
    href: '/games/slots?theme=dark-joke-rises',
    minBet: 100,
    maxBet: 100000,
    features: ['Joker Wilds', 'Chaos Multiplier', 'Bonus Wheel'],
    theme: 'dark',
    volatility: 'high',
    rtp: 96,
  },
  {
    id: 'zeus-vs-thor',
    slug: 'zeus-vs-thor',
    name: 'Zeus VS Thor',
    category: 'slots',
    description: 'Gods clash on the reels with lightning respins and thunder wilds',
    icon: '⚡',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=zeus-vs-thor',
    minBet: 200,
    maxBet: 100000,
    features: ['Lightning Respins', 'Thunder Wilds', 'God Battle Bonus'],
    theme: 'mythology',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'rainbow-ryan',
    slug: 'rainbow-ryan',
    name: 'Rainbow Ryan',
    category: 'slots',
    description: 'Irish luck themed with rainbow wilds and pot of gold bonus',
    icon: '🌈',
    houseEdge: '3%',
    href: '/games/slots?theme=rainbow-ryan',
    minBet: 100,
    maxBet: 50000,
    features: ['Rainbow Wilds', 'Pot of Gold', 'Free Spins'],
    theme: 'irish',
    volatility: 'medium',
    rtp: 97,
  },
  {
    id: 'avatars-gateway',
    slug: 'avatars-gateway',
    name: 'Avatars Gateway',
    category: 'slots',
    description: 'Spiritual journey through cosmic reels with avatar transformations',
    icon: '🧘',
    houseEdge: '3.8%',
    href: '/games/slots?theme=avatars-gateway',
    minBet: 100,
    maxBet: 75000,
    features: ['Avatar Transform', 'Gateway Bonus', 'Multipliers'],
    theme: 'spiritual',
    volatility: 'medium',
    rtp: 96.2,
  },
  {
    id: 'cleos-heart',
    slug: 'cleos-heart',
    name: "Cleo's Heart",
    category: 'slots',
    description: 'Ancient Egyptian slot with scarab scatters and Cleopatra free spins',
    icon: '💎',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=cleos-heart',
    minBet: 100,
    maxBet: 100000,
    features: ['Scarab Scatters', 'Cleopatra Spins', 'Expanding Wilds'],
    theme: 'egypt',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'clover-stones',
    slug: 'clover-stones',
    name: 'Clover Stones',
    category: 'slots',
    description: 'Lucky Irish stones with clover wilds and gemstone bonus picks',
    icon: '🍀',
    houseEdge: '3%',
    href: '/games/slots?theme=clover-stones',
    minBet: 100,
    maxBet: 50000,
    features: ['Clover Wilds', 'Gemstone Bonus', 'Free Spins'],
    theme: 'irish',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'crazy-scientist',
    slug: 'crazy-scientist',
    name: 'Crazy Scientist',
    category: 'slots',
    description: 'Mad lab experiments with explosive wilds and potion multipliers',
    icon: '🧪',
    houseEdge: '3.5%',
    isNew: true,
    href: '/games/slots?theme=crazy-scientist',
    minBet: 100,
    maxBet: 50000,
    features: ['Explosive Wilds', 'Potion Multiplier', 'Lab Bonus'],
    theme: 'science',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'dragon-sevens',
    slug: 'dragon-sevens',
    name: 'Dragon Sevens',
    category: 'slots',
    description: 'Classic sevens meet fire-breathing dragons with stacked wilds',
    icon: '🐉',
    houseEdge: '3%',
    href: '/games/slots?theme=dragon-sevens',
    minBet: 100,
    maxBet: 75000,
    features: ['Stacked Wilds', 'Dragon Respins', '7s Jackpot'],
    theme: 'fantasy',
    volatility: 'medium',
    rtp: 97,
  },
  {
    id: 'fortune-cash',
    slug: 'fortune-cash',
    name: 'Fortune Cash',
    category: 'slots',
    description: 'Golden fortune reels with cash-on-reels and hold & win mechanic',
    icon: '💰',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=fortune-cash',
    minBet: 100,
    maxBet: 100000,
    features: ['Cash on Reels', 'Hold & Win', 'Grand Jackpot'],
    theme: 'wealth',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'fruit-cash',
    slug: 'fruit-cash',
    name: 'Fruit Cash',
    category: 'slots',
    description: 'Classic fruit machine with modern cash prizes and bonus spins',
    icon: '🍒',
    houseEdge: '2.5%',
    href: '/games/slots?theme=fruit-cash',
    minBet: 100,
    maxBet: 25000,
    features: ['Fruit Wilds', 'Cash Prizes', 'Bonus Spins'],
    theme: 'fruits',
    volatility: 'low',
    rtp: 97.5,
  },
  {
    id: 'hit-in-vegas',
    slug: 'hit-in-vegas',
    name: 'Hit In Vegas',
    category: 'slots',
    description: 'Vegas strip experience with neon wilds and showgirl free spins',
    icon: '🎲',
    houseEdge: '3.5%',
    href: '/games/slots?theme=hit-in-vegas',
    minBet: 200,
    maxBet: 100000,
    features: ['Neon Wilds', 'Showgirl Spins', 'Vegas Jackpot'],
    theme: 'vegas',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'magic-dragons',
    slug: 'magic-dragons',
    name: 'Magic Dragons',
    category: 'slots',
    description: 'Enchanted dragon lair with magic orb scatters and dragon respins',
    icon: '🐲',
    houseEdge: '3.5%',
    href: '/games/slots?theme=magic-dragons',
    minBet: 100,
    maxBet: 50000,
    features: ['Magic Orb Scatters', 'Dragon Respins', 'Treasure Bonus'],
    theme: 'fantasy',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'magic-tree',
    slug: 'magic-tree',
    name: 'Magic Tree',
    category: 'slots',
    description: 'Enchanted forest with growing wilds and fairy free spins',
    icon: '🌳',
    houseEdge: '3%',
    href: '/games/slots?theme=magic-tree',
    minBet: 100,
    maxBet: 50000,
    features: ['Growing Wilds', 'Fairy Spins', 'Nature Bonus'],
    theme: 'nature',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'mma-legends',
    slug: 'mma-legends',
    name: 'MMA Legends',
    category: 'slots',
    description: 'Octagon showdown with knockout wilds and championship bonus',
    icon: '🥊',
    houseEdge: '3.5%',
    isNew: true,
    href: '/games/slots?theme=mma-legends',
    minBet: 200,
    maxBet: 75000,
    features: ['Knockout Wilds', 'Championship Bonus', 'Fight Respins'],
    theme: 'sports',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'space-rocks',
    slug: 'space-rocks',
    name: 'Space Rocks',
    category: 'slots',
    description: 'Asteroid field reels with gravity wilds and supernova multipliers',
    icon: '🚀',
    houseEdge: '3.8%',
    href: '/games/slots?theme=space-rocks',
    minBet: 100,
    maxBet: 50000,
    features: ['Gravity Wilds', 'Supernova Multiplier', 'Asteroid Bonus'],
    theme: 'space',
    volatility: 'high',
    rtp: 96.2,
  },
  {
    id: 'volcano-fruits',
    slug: 'volcano-fruits',
    name: 'Volcano Fruits',
    category: 'slots',
    description: 'Tropical volcano with eruption wilds and lava flow free spins',
    icon: '🌋',
    houseEdge: '3%',
    href: '/games/slots?theme=volcano-fruits',
    minBet: 100,
    maxBet: 50000,
    features: ['Eruption Wilds', 'Lava Flow Spins', 'Fruit Multipliers'],
    theme: 'tropical',
    volatility: 'medium',
    rtp: 97,
  },
  {
    id: 'wild-buffalo',
    slug: 'wild-buffalo',
    name: 'Wild Buffalo',
    category: 'slots',
    description: 'American frontier with stampede wilds and sunset free spins',
    icon: '🦬',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=wild-buffalo',
    minBet: 100,
    maxBet: 100000,
    features: ['Stampede Wilds', 'Sunset Spins', 'Buffalo Grand'],
    theme: 'wildlife',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'vikings-go-wild',
    slug: 'vikings-go-wild',
    name: 'Vikings Go Wild',
    category: 'slots',
    description: 'Norse warriors on the high seas with sticky wilds and rage spins',
    icon: '⚔️',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=vikings-go-wild',
    minBet: 100,
    maxBet: 75000,
    features: ['Sticky Wilds', 'Rage Spins', 'Treasure Chest'],
    theme: 'viking',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'penguin-city',
    slug: 'penguin-city',
    name: 'Penguin City',
    category: 'slots',
    description: 'Icy urban adventure with penguin wilds and igloo bonus picks',
    icon: '🐧',
    houseEdge: '3%',
    href: '/games/slots?theme=penguin-city',
    minBet: 100,
    maxBet: 50000,
    features: ['Penguin Wilds', 'Igloo Bonus', 'Sliding Respins'],
    theme: 'arctic',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'valley-of-gods',
    slug: 'valley-of-gods',
    name: 'Valley of Gods',
    category: 'slots',
    description: 'Ancient temple reels with god power respins and scarab multipliers',
    icon: '🏛️',
    houseEdge: '3.5%',
    href: '/games/slots?theme=valley-of-gods',
    minBet: 100,
    maxBet: 75000,
    features: ['God Power Respins', 'Scarab Multiplier', 'Temple Bonus'],
    theme: 'egypt',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'trolls-bridge',
    slug: 'trolls-bridge',
    name: 'Trolls Bridge',
    category: 'slots',
    description: 'Fantasy bridge crossing with troll wilds and golden pick bonus',
    icon: '🧌',
    houseEdge: '3.5%',
    href: '/games/slots?theme=trolls-bridge',
    minBet: 100,
    maxBet: 50000,
    features: ['Troll Wilds', 'Golden Pick', 'Bridge Bonus'],
    theme: 'fantasy',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'nirvana',
    slug: 'nirvana',
    name: 'Nirvana',
    category: 'slots',
    description: 'Transcendent slot with meditation wilds and enlightenment free spins',
    icon: '☯️',
    houseEdge: '3%',
    href: '/games/slots?theme=nirvana',
    minBet: 100,
    maxBet: 50000,
    features: ['Meditation Wilds', 'Enlightenment Spins', 'Karma Multiplier'],
    theme: 'spiritual',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'champions-of-rome',
    slug: 'champions-of-rome',
    name: 'Champions of Rome',
    category: 'slots',
    description: 'Gladiator arena with champion wilds and colosseum free spins',
    icon: '🏟️',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=champions-of-rome',
    minBet: 200,
    maxBet: 100000,
    features: ['Champion Wilds', 'Colosseum Spins', 'Gladiator Bonus'],
    theme: 'roman',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'blood-moon-wilds',
    slug: 'blood-moon-wilds',
    name: 'Blood Moon Wilds',
    category: 'slots',
    description: 'Werewolf-themed with blood moon respins and howling multipliers',
    icon: '🌕',
    houseEdge: '4%',
    href: '/games/slots?theme=blood-moon-wilds',
    minBet: 100,
    maxBet: 75000,
    features: ['Blood Moon Respins', 'Howling Multiplier', 'Wolf Pack Bonus'],
    theme: 'horror',
    volatility: 'high',
    rtp: 96,
  },
  {
    id: 'pumpkin-smash',
    slug: 'pumpkin-smash',
    name: 'Pumpkin Smash',
    category: 'slots',
    description: 'Halloween themed with smashing pumpkin bonus and ghost wilds',
    icon: '🎃',
    houseEdge: '3.5%',
    href: '/games/slots?theme=pumpkin-smash',
    minBet: 100,
    maxBet: 50000,
    features: ['Pumpkin Smash Bonus', 'Ghost Wilds', 'Trick or Treat Spins'],
    theme: 'halloween',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'hades-gigablox',
    slug: 'hades-gigablox',
    name: 'Hades Gigablox',
    category: 'slots',
    description: 'Underworld reels with gigantic symbol blocks and Hades free spins',
    icon: '💀',
    houseEdge: '4%',
    isHot: true,
    href: '/games/slots?theme=hades-gigablox',
    minBet: 200,
    maxBet: 100000,
    features: ['Gigablox Symbols', 'Hades Spins', 'Cerberus Wild'],
    theme: 'mythology',
    volatility: 'high',
    rtp: 96,
  },
  {
    id: 'hanzos-dojo',
    slug: 'hanzos-dojo',
    name: "Hanzo's Dojo",
    category: 'slots',
    description: 'Japanese warrior slot with katana wilds and dojo free spins',
    icon: '🥷',
    houseEdge: '3.5%',
    href: '/games/slots?theme=hanzos-dojo',
    minBet: 100,
    maxBet: 75000,
    features: ['Katana Wilds', 'Dojo Spins', 'Shuriken Scatter'],
    theme: 'japanese',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'golden-pharaoh',
    slug: 'golden-pharaoh',
    name: 'Golden Pharaoh',
    category: 'slots',
    description: 'Pyramid treasure hunt with golden scarab wilds and tomb bonus',
    icon: '🏺',
    houseEdge: '3.5%',
    href: '/games/slots?theme=golden-pharaoh',
    minBet: 100,
    maxBet: 75000,
    features: ['Golden Scarab Wilds', 'Tomb Bonus', 'Pyramid Jackpot'],
    theme: 'egypt',
    volatility: 'medium',
    rtp: 96.5,
  },
  {
    id: 'ocean-treasure',
    slug: 'ocean-treasure',
    name: 'Ocean Treasure',
    category: 'slots',
    description: 'Deep sea diving with mermaid wilds and sunken treasure bonus',
    icon: '🧜‍♀️',
    houseEdge: '3%',
    href: '/games/slots?theme=ocean-treasure',
    minBet: 100,
    maxBet: 50000,
    features: ['Mermaid Wilds', 'Sunken Treasure', 'Deep Dive Spins'],
    theme: 'ocean',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'samurai-path',
    slug: 'samurai-path',
    name: 'Samurai Path',
    category: 'slots',
    description: 'Bushido code reels with honor wilds and samurai showdown bonus',
    icon: '⛩️',
    houseEdge: '3.5%',
    isNew: true,
    href: '/games/slots?theme=samurai-path',
    minBet: 200,
    maxBet: 75000,
    features: ['Honor Wilds', 'Samurai Showdown', 'Cherry Blossom Spins'],
    theme: 'japanese',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'neon-rush',
    slug: 'neon-rush',
    name: 'Neon Rush',
    category: 'slots',
    description: 'Cyberpunk city with neon stacked wilds and turbo respins',
    icon: '💜',
    houseEdge: '3.5%',
    isNew: true,
    href: '/games/slots?theme=neon-rush',
    minBet: 100,
    maxBet: 50000,
    features: ['Neon Stacked Wilds', 'Turbo Respins', 'Cyber Bonus'],
    theme: 'cyberpunk',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'pirate-gold',
    slug: 'pirate-gold',
    name: 'Pirate Gold',
    category: 'slots',
    description: 'Swashbuckling adventure with treasure map bonus and ship wilds',
    icon: '🏴‍☠️',
    houseEdge: '3%',
    href: '/games/slots?theme=pirate-gold',
    minBet: 100,
    maxBet: 50000,
    features: ['Treasure Map Bonus', 'Ship Wilds', 'Cannon Scatter'],
    theme: 'pirate',
    volatility: 'medium',
    rtp: 97,
  },
  {
    id: 'firelink',
    slug: 'firelink',
    name: 'Firelink',
    category: 'slots',
    description: 'Ultimate fireball feature with lock & respin and grand jackpot',
    icon: '🔥',
    houseEdge: '4%',
    isHot: true,
    href: '/games/slots?theme=firelink',
    minBet: 200,
    maxBet: 100000,
    features: ['Fireball Lock', 'Lock & Respin', 'Grand Jackpot'],
    theme: 'fire',
    volatility: 'high',
    rtp: 96,
  },
  {
    id: 'lucky-koi',
    slug: 'lucky-koi',
    name: 'Lucky Koi',
    category: 'slots',
    description: 'Tranquil koi pond with lucky fish wilds and zen garden bonus',
    icon: '🐟',
    houseEdge: '3%',
    href: '/games/slots?theme=lucky-koi',
    minBet: 100,
    maxBet: 50000,
    features: ['Lucky Fish Wilds', 'Zen Garden Bonus', 'Koi Respins'],
    theme: 'asian',
    volatility: 'low',
    rtp: 97,
  },
  {
    id: 'diamond-mine',
    slug: 'diamond-mine',
    name: 'Diamond Mine',
    category: 'slots',
    description: 'Megaways mine shaft with cascading wins and TNT multipliers',
    icon: '💎',
    houseEdge: '3.5%',
    href: '/games/slots?theme=diamond-mine',
    minBet: 200,
    maxBet: 100000,
    features: ['Megaways', 'Cascading Wins', 'TNT Multiplier'],
    theme: 'mining',
    volatility: 'high',
    rtp: 96.5,
  },
  {
    id: 'wolf-gold',
    slug: 'wolf-gold',
    name: 'Wolf Gold',
    category: 'slots',
    description: 'Howling wolf reels with money respin and mega jackpot feature',
    icon: '🐺',
    houseEdge: '3.5%',
    isHot: true,
    href: '/games/slots?theme=wolf-gold',
    minBet: 100,
    maxBet: 75000,
    features: ['Money Respin', 'Mega Jackpot', 'Stacked Wilds'],
    theme: 'wildlife',
    volatility: 'medium',
    rtp: 96.5,
  },
]

// ═══════════════════════════════════════════════════
//  HELPER FUNCTIONS
// ═══════════════════════════════════════════════════

export function getGamesByCategory(category: GameInfo['category']): GameInfo[] {
  return GAME_CATALOG.filter((g) => g.category === category)
}

export function getFeaturedGames(): GameInfo[] {
  return GAME_CATALOG.filter((g) => g.isHot || g.isNew)
}

export function searchGames(query: string): GameInfo[] {
  const q = query.toLowerCase().trim()
  if (!q) return GAME_CATALOG
  return GAME_CATALOG.filter(
    (g) =>
      g.name.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.theme?.toLowerCase().includes(q) ||
      g.features?.some((f) => f.toLowerCase().includes(q))
  )
}

export function getGameBySlug(slug: string): GameInfo | undefined {
  return GAME_CATALOG.find((g) => g.slug === slug)
}

export function getGameCount(category?: string): number {
  if (!category || category === 'all') return GAME_CATALOG.length
  if (category === 'favorites') return 0 // resolved at runtime
  return GAME_CATALOG.filter((g) => g.category === category).length
}
